### ISSUE TITLE
79:154 execution error

### ISSUE THREAD

**Issue by GiovanniGrieco** [AdRoll/AirControl#1]
Hi. I've tried to run aircontrol following your Readme file but Terminal.app returns me this error:

`79:154: execution error: System Events got an error: Can’t get menu bar item 1 of menu bar 1 of process "SystemUIServer" whose description contains "Displays". Invalid index. (-1719)`

I'm using OS X Yosemite. Thanks for your support and keep up the good work!

**Comment by Timothee** [comment]
@corsaroquad sorry I missed your now year-old message! In case you're still interested, I'd first check if you have a "Displays" menu. It looks like this in your system bar:

<img width="32" alt="screen shot 2015-11-16 at 12 15 10 pm" src="https://cloud.githubusercontent.com/assets/159328/11193473/ba6b2cac-8c5b-11e5-9459-88c9bd2d1590.png">

If you don't have it, I'd check this option in the System Preferences/Displays:
<img width="668" alt="system_preferences_-_displays" src="https://cloud.githubusercontent.com/assets/159328/11193485/ca42ff7e-8c5b-11e5-83fe-4e8bf80ce4c2.png">

The error above comes from the AppleScript we're using and indicates that it can't find the menu. Another possibility would be that your OS' language is not English. Then you'd want to check for the translation used and modify the script in the right place.

Hope that helps! (better late than never :smile: )
