### ISSUE TITLE
Update for Sierra?

### ISSUE THREAD

**Issue by turntablez** [AdRoll/AirControl#3]
Hi, Love this, not too up on my apple script though. Any chance you can update it to work in sierra?
Thanks

**Comment by Timothee** [comment]
@turntablez just seeing this. (I can never figure out the right notification settings in GitHub evidently…)

I don't have Sierra yet, so not sure what's needed to make it work there. I assume it's not working at all? Do you have any message you can share here?

**Comment by santiagosnchez** [comment]
Not working at all with Sierra. I'm getting:

$ aircontrol Apple\ TV
306:312: execution error: System Events got an error: Can’t get menu bar item 2 of menu bar 1 of process "SystemUIServer" whose description contains "Displays Menu". Invalid index. (-1719)

**Comment by Timothee** [comment]
@santiagosnchez thanks for this. I'll see if I can get my hands on a Mac with Sierra one of these days. Evidently, it shouldn't be too hard to fix, it just can't find the right menu, or the index is off or something…

It looks like the auto-completion is not an issue at least.

**Comment by Timothee** [comment]
@santiagosnchez @turntablez could one of you try the change I proposed here: https://github.com/AdRoll/AirControl/pull/4

The change just uses the original code that didn't work with El Capitan. As mentioned in the description, I wasn't able to test it fully but I'm confident enough to ask you to try it.

Thanks!

**Comment by santiagosnchez** [comment]
I'll be able to test it, but until Monday next week. Thanks for looking into it --I think its a really nice tool.

**Comment by Timothee** [comment]
I was going to ask if your OS was in a language other than English but based on the error you're getting, it seems to be English. Unless there's a difference between the various "Englishes".

I can't seem to find a reliable attribute to go by… (i.e., no unique ID that I can find)

@santiagosnchez glad you like it! I don't use it anymore because we don't use AppleTVs anymore at work…

**Comment by Timothee** [comment]
@santiagosnchez did you get a chance to try it?

**Comment by santiagosnchez** [comment]
@Timothee Nope, not yet! I'll remember to take my mac mini (which runs Sierra) home from my office during the weekend. Its the only place I have access to an AppleTV.

**Comment by sagarkm** [comment]
Awaiting fix for Sierra

**Comment by Timothee** [comment]
I recently got a Mac running Sierra so I should be able to give it a try soon-ish… (need to set up an Apple TV first)

**Comment by Timothee** [comment]
@sagarkm @santiagosnchez I got to try things with Sierra directly. Please check that branch in #4.
As noted in the second git commit message, there are still some oddities. That menu doesn't behave like it did for previous macOS versions and I've had inconsistent results.

It **mostly** works, so if you could try it, that would be great.

**Comment by Timothee** [comment]
The fix from #4 works for me. Closing this one.
